version: 0.2

env:
  # RSS_READER_IMAGE_URI
  # LINK_READER_IMAGE_URI
  # EMAIL_READER_IMAGE_URI
  # SCRAPER_IMAGE_URI
  # SUMMARIZER_IMAGE_URI
  # DIGEST_IMAGE_URI
  # IMMEDIATE_IMAGE_URI
  exported-variables:
    - CODEBUILD_BUILD_ID

phases:
  install:
    commands:
      - echo RSS_READER_IMAGE_URI=${RSS_READER_IMAGE_URI}
      - echo LINK_READER_IMAGE_URI=${LINK_READER_IMAGE_URI}
      - echo EMAIL_READER_IMAGE_URI=${EMAIL_READER_IMAGE_URI}
      - echo SCRAPER_IMAGE_URI=${SCRAPER_IMAGE_URI}
      - echo SUMMARIZER_IMAGE_URI=${SUMMARIZER_IMAGE_URI}
      - echo DIGEST_IMAGE_URI=${DIGEST_IMAGE_URI}
      - echo IMMEDIATE_IMAGE_URI=${IMMEDIATE_IMAGE_URI}
      - terraform --version

  pre_build:
    commands:
      - cd cicd/app/terraform
      - ls -la
      - terraform init --plugin-dir /tf-plugins -reconfigure

  build:
    commands:
      - BUILD_ID=${CODEBUILD_BUILD_ID##*:}
      - echo BUILD_ID=${BUILD_ID}
      - ls -la
      - terraform apply
        -var=rss_reader_image_uri=${RSS_READER_IMAGE_URI}
        -var=link_reader_image_uri=${LINK_READER_IMAGE_URI}
        -var=email_reader_image_uri=${EMAIL_READER_IMAGE_URI}
        -var=scraper_image_uri=${SCRAPER_IMAGE_URI}
        -var=summarizer_image_uri=${SUMMARIZER_IMAGE_URI}
        -var=digest_image_uri=${DIGEST_IMAGE_URI}
        -var=immediate_image_uri=${IMMEDIATE_IMAGE_URI}
        -var=build_id=${BUILD_ID}
        -auto-approve
