version: 0.2

# env vars provided by the pipeline:
# PIPELINE_EXECUTION_ID

env:
  exported-variables:
    - SUMMARIZER_IMAGE_URI

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - echo AWS_ACCOUNT_ID=${AWS_ACCOUNT_ID}
      - echo PIPELINE_EXECUTION_ID=${PIPELINE_EXECUTION_ID}

  pre_build:
    commands:
      - aws ecr get-login-password --region ${AWS_DEFAULT_REGION} |
        docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com

  build:
    commands:
      - docker build -f src/summarizer/Dockerfile -t dailymail-summarizer .

  post_build:
    commands:
      - SUMMARIZER_IMAGE_URI=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/dailymail-summarizer:$PIPELINE_EXECUTION_ID
      - echo $SUMMARIZER_IMAGE_URI
      - docker tag dailymail-summarizer $SUMMARIZER_IMAGE_URI
      - docker push $SUMMARIZER_IMAGE_URI
