version: 0.2

env:
  # AWS_ACCOUNT_ID
  exported-variables:
    - CODEBUILD_BUILD_ID
    - RSS_READER_IMAGE_URI
    - SCRAPER_IMAGE_URI
    - BUILD_ID

phases:
  install:
    runtime-versions:
      python: 3.12

  pre_build:
    commands:
      - aws ecr get-login-password --region ${AWS_DEFAULT_REGION} |
        docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com

  build:
    commands:
      - cd src/rss_reader
      - docker build -f Dockerfile -t DailyMail-RssReader .
      - cd ../link_scraper
      - docker build -f Dockerfile -t DailyMail-Scraper .

  post_build:
    commands:
      - BUILD_ID=${CODEBUILD_BUILD_ID##*:}
      - RSS_READER_IMAGE_URI=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/DailyMail-RssReader:$BUILD_ID
      - echo $RSS_READER_IMAGE_URI
      - docker tag DailyMail-RssReader $RSS_READER_IMAGE_URI
      - docker push $RSS_READER_IMAGE_URI
      - SCRAPER_IMAGE_URI=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/DailyMail-Scraper:$BUILD_ID
      - echo $SCRAPER_IMAGE_URI
      - docker tag DailyMail-Scraper $SCRAPER_IMAGE_URI
      - docker push $SCRAPER_IMAGE_URI
