version: 0.2

env:
  # AWS_ACCOUNT_ID
  exported-variables:
    - CODEBUILD_BUILD_ID
    - RSS_READER_IMAGE_URI
    - LINK_READER_IMAGE_URI
    - SCRAPER_IMAGE_URI
    - SUMMARIZER_IMAGE_URI
    - DIGEST_IMAGE_URI
    - IMMEDIATE_IMAGE_URI
    - BUILD_ID

phases:
  install:
    runtime-versions:
      python: 3.12

  pre_build:
    commands:
      - aws ecr get-login-password --region ${AWS_DEFAULT_REGION} |
        docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com

  build:
    commands:
      - cd src
      - for symlink in */shared; do rm -f "$symlink"; cp -R shared $(dirname "$symlink"); done
      - find . -type f | sort
      - cd rss_reader
      - docker build -f Dockerfile -t dailymail-rss-reader .
      - cd ../link_reader
      - docker build -f Dockerfile -t dailymail-link-reader .
      - cd ../scraper
      - docker build -f Dockerfile -t dailymail-scraper .
      - cd ../summarizer
      - docker build -f Dockerfile -t dailymail-summarizer .
      - cd ../digest
      - docker build -f Dockerfile -t dailymail-digest .
      - cd ../immediate
      - docker build -f Dockerfile -t dailymail-immediate .

  post_build:
    commands:
      - BUILD_ID=${CODEBUILD_BUILD_ID##*:}
      - RSS_READER_IMAGE_URI=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/dailymail-rss-reader:$BUILD_ID
      - echo $RSS_READER_IMAGE_URI
      - docker tag dailymail-rss-reader $RSS_READER_IMAGE_URI
      - docker push $RSS_READER_IMAGE_URI
      - LINK_READER_IMAGE_URI=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/dailymail-link-reader:$BUILD_ID
      - echo $LINK_READER_IMAGE_URI
      - docker tag dailymail-link-reader $LINK_READER_IMAGE_URI
      - docker push $LINK_READER_IMAGE_URI
      - SCRAPER_IMAGE_URI=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/dailymail-scraper:$BUILD_ID
      - echo $SCRAPER_IMAGE_URI
      - docker tag dailymail-scraper $SCRAPER_IMAGE_URI
      - docker push $SCRAPER_IMAGE_URI
      - SUMMARIZER_IMAGE_URI=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/dailymail-summarizer:$BUILD_ID
      - echo $SUMMARIZER_IMAGE_URI
      - docker tag dailymail-summarizer $SUMMARIZER_IMAGE_URI
      - docker push $SUMMARIZER_IMAGE_URI
      - DIGEST_IMAGE_URI=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/dailymail-digest:$BUILD_ID
      - echo $DIGEST_IMAGE_URI
      - docker tag dailymail-digest $DIGEST_IMAGE_URI
      - docker push $DIGEST_IMAGE_URI
      - IMMEDIATE_IMAGE_URI=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/dailymail-immediate:$BUILD_ID
      - echo $IMMEDIATE_IMAGE_URI
      - docker tag dailymail-immediate $IMMEDIATE_IMAGE_URI
      - docker push $IMMEDIATE_IMAGE_URI
